-- Comprehensive Schema Update for Campus-Ease
-- Run this in Supabase SQL Editor to align all tables

-- ================================================================
-- 1. UPDATE CLASS_DETAILS TABLE
-- ================================================================
DO $$
BEGIN
  -- Ensure class_details table exists with proper structure
  CREATE TABLE IF NOT EXISTS public.class_details (
    id bigint generated by default as identity not null,
    class_name text not null,
    class_id text unique not null,
    department text not null,
    institute text not null,
    semester integer not null default 1,
    academic_year text not null,
    description text,
    course_taken text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint class_details_pkey primary key (id),
    constraint unique_class_id unique (class_id)
  );

  RAISE NOTICE 'Class details table structure verified';
END
$$;

-- ================================================================
-- 2. UPDATE STUDENT_RECORDS TABLE
-- ================================================================
DO $$
BEGIN
  -- First, ensure the table exists
  CREATE TABLE IF NOT EXISTS public.student_records (
    id bigint generated by default as identity not null,
    user_id text unique not null,
    auth_id uuid null,
    fname text not null,
    lname text not null,
    email text unique not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint student_records_pkey primary key (id),
    constraint unique_student_user_id unique (user_id),
    constraint unique_student_email unique (email)
  );

  -- Add missing columns if they don't exist
  
  -- Add mobile_num column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'student_records' AND column_name = 'mobile_num'
  ) THEN
    ALTER TABLE public.student_records ADD COLUMN mobile_num text;
  END IF;

  -- Add roll_no column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'student_records' AND column_name = 'roll_no'
  ) THEN
    ALTER TABLE public.student_records ADD COLUMN roll_no text;
  END IF;

  -- Add dob column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'student_records' AND column_name = 'dob'
  ) THEN
    ALTER TABLE public.student_records ADD COLUMN dob date;
  END IF;

  -- Add address column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'student_records' AND column_name = 'address'
  ) THEN
    ALTER TABLE public.student_records ADD COLUMN address text;
  END IF;

  -- Add emergency_contact column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'student_records' AND column_name = 'emergency_contact'
  ) THEN
    ALTER TABLE public.student_records ADD COLUMN emergency_contact text;
  END IF;

  -- Add course_taken column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'student_records' AND column_name = 'course_taken'
  ) THEN
    ALTER TABLE public.student_records ADD COLUMN course_taken text;
  END IF;

  -- Add class_id column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'student_records' AND column_name = 'class_id'
  ) THEN
    ALTER TABLE public.student_records ADD COLUMN class_id text;
  END IF;

  -- Add department column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'student_records' AND column_name = 'department'
  ) THEN
    ALTER TABLE public.student_records ADD COLUMN department text;
  END IF;

  -- Add institute column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'student_records' AND column_name = 'institute'
  ) THEN
    ALTER TABLE public.student_records ADD COLUMN institute text DEFAULT 'CHARUSAT';
  END IF;

  -- Add semester column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'student_records' AND column_name = 'semester'
  ) THEN
    ALTER TABLE public.student_records ADD COLUMN semester integer DEFAULT 1;
  END IF;

  -- Add academic_year column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'student_records' AND column_name = 'academic_year'
  ) THEN
    ALTER TABLE public.student_records ADD COLUMN academic_year text;
  END IF;

  -- Add role column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'student_records' AND column_name = 'role'
  ) THEN
    ALTER TABLE public.student_records ADD COLUMN role text DEFAULT 'student';
  END IF;

  -- Add email_verified column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'student_records' AND column_name = 'email_verified'
  ) THEN
    ALTER TABLE public.student_records ADD COLUMN email_verified boolean DEFAULT false;
  END IF;

  -- Add account_activated column
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'student_records' AND column_name = 'account_activated'
  ) THEN
    ALTER TABLE public.student_records ADD COLUMN account_activated boolean DEFAULT false;
  END IF;

  -- Handle existing student_id column if it exists and has NOT NULL constraint
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'student_records' AND column_name = 'student_id'
  ) THEN
    -- First, populate student_id with user_id if it's null
    UPDATE public.student_records 
    SET student_id = user_id 
    WHERE student_id IS NULL;
    
    -- If student_id still exists and we want to remove it, we need to drop NOT NULL constraint first
    ALTER TABLE public.student_records ALTER COLUMN student_id DROP NOT NULL;
  END IF;

  -- Update existing data to have proper structure
  -- Set roll_no = user_id if roll_no is null
  UPDATE public.student_records 
  SET roll_no = user_id 
  WHERE roll_no IS NULL OR roll_no = '';

  -- Extract department from existing data patterns
  UPDATE public.student_records 
  SET department = CASE
    WHEN user_id LIKE '%DIT%' OR course_taken LIKE '%DIT%' THEN 'DIT'
    WHEN user_id LIKE '%IT%' OR course_taken LIKE '%IT%' THEN 'IT'
    WHEN user_id LIKE '%CE%' OR course_taken LIKE '%CE%' THEN 'CE'
    WHEN user_id LIKE '%CS%' OR course_taken LIKE '%CS%' THEN 'CS'
    ELSE 'DIT'
  END
  WHERE department IS NULL OR department = '';

  -- Set default academic year
  UPDATE public.student_records 
  SET academic_year = '2024-25'
  WHERE academic_year IS NULL OR academic_year = '';

  -- Add unique constraint on roll_no if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_name = 'unique_student_roll_no'
    AND table_name = 'student_records'
  ) THEN
    -- Remove duplicates first
    DELETE FROM public.student_records 
    WHERE id IN (
      SELECT id FROM (
        SELECT id, ROW_NUMBER() OVER (PARTITION BY roll_no ORDER BY id) as rnum
        FROM public.student_records 
        WHERE roll_no IS NOT NULL
      ) t WHERE t.rnum > 1
    );
    
    -- Add unique constraint
    ALTER TABLE public.student_records 
    ADD CONSTRAINT unique_student_roll_no 
    UNIQUE (roll_no);
  END IF;

  RAISE NOTICE 'Student records table structure updated with all columns';
END
$$;

-- ================================================================
-- 2B. ADD FOREIGN KEY CONSTRAINTS TO STUDENT_RECORDS
-- ================================================================
DO $$
BEGIN
  -- Add foreign key to class_details if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_name = 'fk_student_class'
    AND table_name = 'student_records'
  ) THEN
    -- Only add if class_details table exists
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'class_details') THEN
      ALTER TABLE public.student_records 
      ADD CONSTRAINT fk_student_class 
      FOREIGN KEY (class_id) 
      REFERENCES public.class_details(class_id) 
      ON DELETE SET NULL;
      
      RAISE NOTICE 'Added foreign key constraint to class_details';
    END IF;
  END IF;

  -- Add foreign key to auth.users if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_name = 'fk_student_auth'
    AND table_name = 'student_records'
  ) THEN
    ALTER TABLE public.student_records 
    ADD CONSTRAINT fk_student_auth 
    FOREIGN KEY (auth_id) 
    REFERENCES auth.users(id) 
    ON DELETE SET NULL;
    
    RAISE NOTICE 'Added foreign key constraint to auth.users';
  END IF;
END
$$;

-- ================================================================
-- 3. UPDATE ATTENDANCE TABLE
-- ================================================================
DO $$
BEGIN
  -- Create attendance table if it doesn't exist
  CREATE TABLE IF NOT EXISTS public.attendance (
    id bigint generated by default as identity not null,
    student_name text not null,
    date date not null,
    subject text not null,
    class_type text not null,
    status text not null check (status in ('present', 'absent', 'late')),
    marked_by text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint attendance_pkey primary key (id)
  );

  -- Add user_id column if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'attendance' AND column_name = 'user_id'
  ) THEN
    ALTER TABLE public.attendance ADD COLUMN user_id text;
  END IF;

  -- Add class_id column if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'attendance' AND column_name = 'class_id'
  ) THEN
    ALTER TABLE public.attendance ADD COLUMN class_id text;
  END IF;

  -- Copy data from student_id to user_id if user_id is null and student_id exists
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'attendance' AND column_name = 'student_id'
  ) THEN
    UPDATE public.attendance 
    SET user_id = student_id 
    WHERE user_id IS NULL AND student_id IS NOT NULL;
  END IF;

  -- Drop old unique constraint if it exists
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_name = 'unique_attendance' 
    AND table_name = 'attendance'
  ) THEN
    ALTER TABLE public.attendance DROP CONSTRAINT unique_attendance;
  END IF;

  -- Add new unique constraint if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_name = 'unique_attendance_record'
    AND table_name = 'attendance'
  ) THEN
    ALTER TABLE public.attendance 
    ADD CONSTRAINT unique_attendance_record 
    UNIQUE (user_id, date, subject, class_id, marked_by);
  END IF;

  -- Drop old student_id column if user_id exists and has data
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'attendance' AND column_name = 'student_id'
  ) AND EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'attendance' AND column_name = 'user_id'
  ) THEN
    ALTER TABLE public.attendance DROP COLUMN IF EXISTS student_id;
  END IF;

  RAISE NOTICE 'Attendance table structure updated';
END
$$;

-- ================================================================
-- 3B. ADD FOREIGN KEY CONSTRAINTS TO ATTENDANCE
-- ================================================================
DO $$
BEGIN
  -- Add foreign key to student_records (only if both tables have the right structure)
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_name = 'fk_attendance_student'
    AND table_name = 'attendance'
  ) AND EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'attendance' AND column_name = 'user_id'
  ) AND EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'student_records' AND column_name = 'user_id'
  ) THEN
    ALTER TABLE public.attendance 
    ADD CONSTRAINT fk_attendance_student 
    FOREIGN KEY (user_id) 
    REFERENCES public.student_records(user_id) 
    ON DELETE CASCADE;
    
    RAISE NOTICE 'Added foreign key constraint from attendance to student_records';
  END IF;

  -- Add foreign key to class_details
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE constraint_name = 'fk_attendance_class'
    AND table_name = 'attendance'
  ) AND EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'attendance' AND column_name = 'class_id'
  ) AND EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_name = 'class_details'
  ) THEN
    ALTER TABLE public.attendance 
    ADD CONSTRAINT fk_attendance_class 
    FOREIGN KEY (class_id) 
    REFERENCES public.class_details(class_id) 
    ON DELETE SET NULL;
    
    RAISE NOTICE 'Added foreign key constraint from attendance to class_details';
  END IF;
END
$$;

-- ================================================================
-- 4. CREATE INDEXES FOR PERFORMANCE
-- ================================================================
-- Class details indexes
CREATE INDEX IF NOT EXISTS idx_class_details_department ON public.class_details USING btree (department);
CREATE INDEX IF NOT EXISTS idx_class_details_institute ON public.class_details USING btree (institute);
CREATE INDEX IF NOT EXISTS idx_class_details_academic_year ON public.class_details USING btree (academic_year);
CREATE INDEX IF NOT EXISTS idx_class_details_class_id ON public.class_details USING btree (class_id);

-- Student records indexes
CREATE INDEX IF NOT EXISTS idx_student_records_user_id ON public.student_records USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_student_records_class_id ON public.student_records USING btree (class_id);
CREATE INDEX IF NOT EXISTS idx_student_records_department ON public.student_records USING btree (department);
CREATE INDEX IF NOT EXISTS idx_student_records_roll_no ON public.student_records USING btree (roll_no);
CREATE INDEX IF NOT EXISTS idx_student_records_email ON public.student_records USING btree (email);

-- Attendance indexes
CREATE INDEX IF NOT EXISTS idx_attendance_user_id ON public.attendance USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_attendance_class_id ON public.attendance USING btree (class_id);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON public.attendance USING btree (date DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_subject ON public.attendance USING btree (subject);

-- ================================================================
-- 5. INSERT SAMPLE DATA FOR TESTING
-- ================================================================
-- Insert sample departments/classes
INSERT INTO public.class_details (class_name, class_id, department, institute, semester, academic_year, course_taken)
VALUES 
  ('DIT Sem 7', '24DIT1658', 'DIT', 'DEPSTAR', 7, '2024-25', 'B.Tech DIT - DEPSTAR'),
  ('IT Sem 5', '24IT1659', 'IT', 'CSPIT', 5, '2024-25', 'B.Tech IT - CSPIT'),
  ('CE Sem 3', '24CE1660', 'CE', 'CSPIT', 3, '2024-25', 'B.Tech CE - CSPIT'),
  ('CS Sem 6', '24CS1661', 'CS', 'DEPSTAR', 6, '2024-25', 'B.Tech CS - DEPSTAR')
ON CONFLICT (class_id) DO NOTHING;

-- Insert sample students
INSERT INTO public.student_records (
  user_id, fname, lname, email, roll_no, student_id, class_id, department, institute, semester, academic_year, course_taken
)
VALUES 
  -- DIT Students
  ('24DIT001', 'Yash', 'Ahir', '24dit001@charusat.edu.in', '24DIT001', '24DIT001', '24DIT1658', 'DIT', 'DEPSTAR', 7, '2024-25', 'B.Tech DIT - DEPSTAR'),
  ('24DIT002', 'Harsh', 'Shah', '24dit002@charusat.edu.in', '24DIT002', '24DIT002', '24DIT1658', 'DIT', 'DEPSTAR', 7, '2024-25', 'B.Tech DIT - DEPSTAR'),
  ('24DIT003', 'Priya', 'Patel', '24dit003@charusat.edu.in', '24DIT003', '24DIT003', '24DIT1658', 'DIT', 'DEPSTAR', 7, '2024-25', 'B.Tech DIT - DEPSTAR'),
  
  -- IT Students  
  ('24IT001', 'Rahul', 'Kumar', '24it001@charusat.edu.in', '24IT001', '24IT001', '24IT1659', 'IT', 'CSPIT', 5, '2024-25', 'B.Tech IT - CSPIT'),
  ('24IT002', 'Sneha', 'Sharma', '24it002@charusat.edu.in', '24IT002', '24IT002', '24IT1659', 'IT', 'CSPIT', 5, '2024-25', 'B.Tech IT - CSPIT'),
  
  -- CE Students
  ('24CE001', 'Amit', 'Joshi', '24ce001@charusat.edu.in', '24CE001', '24CE001', '24CE1660', 'CE', 'CSPIT', 3, '2024-25', 'B.Tech CE - CSPIT'),
  ('24CE002', 'Kavya', 'Modi', '24ce002@charusat.edu.in', '24CE002', '24CE002', '24CE1660', 'CE', 'CSPIT', 3, '2024-25', 'B.Tech CE - CSPIT')
ON CONFLICT (user_id) DO NOTHING;

-- ================================================================
-- 6. VERIFICATION QUERIES
-- ================================================================
-- Check table structures
SELECT 'Class Details' as table_name, count(*) as row_count FROM public.class_details
UNION ALL
SELECT 'Student Records' as table_name, count(*) as row_count FROM public.student_records
UNION ALL
SELECT 'Attendance' as table_name, count(*) as row_count FROM public.attendance;

-- Show sample data
SELECT 
  cd.class_name,
  cd.department,
  cd.class_id,
  COUNT(sr.user_id) as student_count
FROM public.class_details cd
LEFT JOIN public.student_records sr ON cd.class_id = sr.class_id
GROUP BY cd.class_name, cd.department, cd.class_id
ORDER BY cd.department;