create table public.report (
  id bigint generated by default as identity not null,
  "Problem_Category" text null,
  "Reporter_Type" text null,
  "Location" text null,
  "class_No" bigint null,
  "Impact_Scope" text null,
  "Occurrence_Pattern" text null,
  images text null,
  priority_level integer null default 1,
  priority_text text null default 'Medium'::text,
  description jsonb null,
  resolved boolean null default false,
  resolved_at timestamp with time zone null,
  reporter_id uuid null,
  constraint report_pkey primary key (id),
  constraint fk_reporter foreign key (reporter_id) references auth.users(id)
) TABLESPACE pg_default;

create index IF not exists idx_report_priority on public.report using btree (priority_level desc) TABLESPACE pg_default;
create index IF not exists idx_report_reporter on public.report using btree (reporter_id) TABLESPACE pg_default;

-- Community Messages Table
create table public.community_messages (
  id bigint generated by default as identity not null,
  sender_id uuid not null,
  sender_name text not null,
  sender_role text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  college_id text not null,
  constraint community_messages_pkey primary key (id),
  constraint fk_sender foreign key (sender_id) references auth.users(id)
) TABLESPACE pg_default;

create index IF not exists idx_community_messages_created_at on public.community_messages using btree (created_at desc) TABLESPACE pg_default;
create index IF not exists idx_community_messages_sender on public.community_messages using btree (sender_id) TABLESPACE pg_default; 

-- Attendance Table
create table public.attendance (
  id bigint generated by default as identity not null,
  student_id text not null,
  student_name text not null,
  date date not null,
  subject text not null,
  class_type text not null,
  status text not null check (status in ('present', 'absent', 'late')),
  marked_by text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint attendance_pkey primary key (id),
  constraint unique_attendance unique (student_id, date, subject, marked_by)
) TABLESPACE pg_default;

create index IF not exists idx_attendance_date on public.attendance using btree (date desc) TABLESPACE pg_default;
create index IF not exists idx_attendance_student on public.attendance using btree (student_id) TABLESPACE pg_default;
create index IF not exists idx_attendance_subject on public.attendance using btree (subject) TABLESPACE pg_default;
create index IF not exists idx_attendance_faculty on public.attendance using btree (marked_by) TABLESPACE pg_default;

-- Class Details Table
create table IF NOT EXISTS public.class_details (
  id bigint generated by default as identity not null,
  class_name text not null,
  class_id text unique not null,
  department text not null,
  institute text not null,
  semester integer not null default 1,
  academic_year text not null,
  description text,
  course_taken text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint class_details_pkey primary key (id),
  constraint unique_class_id unique (class_id)
) TABLESPACE pg_default;

create index IF not exists idx_class_details_department on public.class_details using btree (department) TABLESPACE pg_default;
create index IF not exists idx_class_details_institute on public.class_details using btree (institute) TABLESPACE pg_default;
create index IF not exists idx_class_details_academic_year on public.class_details using btree (academic_year) TABLESPACE pg_default;
create index IF not exists idx_class_details_class_id on public.class_details using btree (class_id) TABLESPACE pg_default;

  -- Student Records Table (for bulk imports and student management)
  create table IF NOT EXISTS public.student_records (
    id bigint generated by default as identity not null,
    user_id text unique not null,
    auth_id uuid null, -- Links to auth.users when account is activated
    fname text not null,
    lname text not null,
    email text unique not null,
    mobile_num bigint null,
    roll_no text not null,
    dob date null,
    address text null,
    emergency_contact bigint null,
    course_taken text null,
    student_id text not null, -- This is the unique student identifier (like roll number)
    class_id text null, -- This links students to classes
    role text default 'student',
    email_verified boolean default false,
    account_activated boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    constraint student_records_pkey primary key (id),
    constraint unique_student_user_id unique (user_id),
    constraint unique_student_email unique (email)
  ) TABLESPACE pg_default;

  -- Add constraints safely with existence checks
  DO $$
  BEGIN
    -- Add class_id column back if it doesn't exist
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns 
      WHERE table_name = 'student_records' AND column_name = 'class_id'
    ) THEN
      ALTER TABLE public.student_records ADD COLUMN class_id text;
    END IF;

    -- Add student_id column if it doesn't exist
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns 
      WHERE table_name = 'student_records' AND column_name = 'student_id'
    ) THEN
      -- First add the column as nullable
      ALTER TABLE public.student_records ADD COLUMN student_id text;
      
      -- Update existing rows to use roll_no as student_id if student_id is null
      UPDATE public.student_records 
      SET student_id = roll_no 
      WHERE student_id IS NULL;
      
      -- Now make it NOT NULL
      ALTER TABLE public.student_records ALTER COLUMN student_id SET NOT NULL;
    END IF;

    -- Add unique roll number constraint 
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.table_constraints 
      WHERE constraint_name = 'unique_student_roll_no'
      AND table_name = 'student_records'
    ) THEN
      ALTER TABLE public.student_records 
      ADD CONSTRAINT unique_student_roll_no 
      UNIQUE (roll_no);
    END IF;

    -- Add foreign key to class_details
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.table_constraints 
      WHERE constraint_name = 'fk_student_class'
      AND table_name = 'student_records'
    ) THEN
      ALTER TABLE public.student_records 
      ADD CONSTRAINT fk_student_class 
      FOREIGN KEY (class_id) 
      REFERENCES public.class_details(class_id) 
      ON DELETE SET NULL;
    END IF;

    -- Add foreign key to auth.users
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.table_constraints 
      WHERE constraint_name = 'fk_student_auth'
      AND table_name = 'student_records'
    ) THEN
      ALTER TABLE public.student_records 
      ADD CONSTRAINT fk_student_auth 
      FOREIGN KEY (auth_id) 
      REFERENCES auth.users(id) 
      ON DELETE SET NULL;
    END IF;
  END
  $$;

  -- Update indexes to use both student_id and class_id
  create index IF not exists idx_student_records_student_id on public.student_records using btree (student_id) TABLESPACE pg_default;
  create index IF not exists idx_student_records_class_id on public.student_records using btree (class_id) TABLESPACE pg_default;
  create index IF not exists idx_student_records_email on public.student_records using btree (email) TABLESPACE pg_default;
  create index IF not exists idx_student_records_roll_no on public.student_records using btree (roll_no) TABLESPACE pg_default;
  create index IF not exists idx_student_records_auth_id on public.student_records using btree (auth_id) TABLESPACE pg_default;

  -- Update existing users table to have optional auth link
  DO $$
  BEGIN
    -- Add auth_id column if it doesn't exist
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns 
      WHERE table_name = 'users' AND column_name = 'auth_id'
    ) THEN
      ALTER TABLE public.users ADD COLUMN auth_id uuid;
      CREATE INDEX IF NOT EXISTS idx_users_auth_id ON public.users USING btree (auth_id);
      
      -- Add foreign key constraint if it doesn't exist
      IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'fk_users_auth'
      ) THEN
        ALTER TABLE public.users 
        ADD CONSTRAINT fk_users_auth 
        FOREIGN KEY (auth_id) 
        REFERENCES auth.users(id) 
        ON DELETE SET NULL;
      END IF;
    END IF;
  END
  $$; 